# docker-compose.deploy.yml
version: '3.8'

volumes:
  userdb_vol:
  productdb_vol:
  orderdb_vol:
  prometheus_data:
  grafana_data:

networks:
  micro_network:
    name: micro_network

services:
  user-api:
    container_name: cuser-service
    build:
      context: ../user-service
    ports:
    - "5001:5001"
    depends_on:
      - user-db
    networks:
      - micro_network
    restart: always

  user-db:
    container_name: cuser_dbase
    image: mysql:8
    ports:
    - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pfm_dc_2020
      MYSQL_DATABASE: user
      MYSQL_USER: cloudacademy
      MYSQL_PASSWORD: pfm_2020
    networks:
      - micro_network
    volumes:
    - userdb_vol:/var/lib/mysql
    

  product-api:
    container_name: cproduct-service
    build:
      context: ../product-service
    ports:
    - "5002:5002"
    depends_on:
      - product-db
    networks:
      - micro_network
    restart: always

  product-db:
    container_name: cproduct_dbase
    image: mysql:8
    ports:
    - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pfm_dc_2020
      MYSQL_DATABASE: product
      MYSQL_USER: cloudacademy
      MYSQL_PASSWORD: pfm_2020
    networks:
      - micro_network
    volumes:
    - productdb_vol:/var/lib/mysql

  order-api:
    container_name: corder-service
    build:
      context: ../order-service
    ports:
    - "5003:5003"
    depends_on:
      - order-db
    networks:
      - micro_network
    restart: always

  order-db:
    container_name: corder_dbase
    image: mysql:8
    ports:
    - "32002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pfm_dc_2020
      MYSQL_DATABASE: order
      MYSQL_USER: cloudacademy
      MYSQL_PASSWORD: pfm_2020
    networks:
      - micro_network
    volumes:
    - orderdb_vol:/var/lib/mysql

  frontend-app:
    container_name: cfrontend-app
    build:
      context: .
    ports:
    - "5000:5000"
    networks:
      - micro_network
    restart: always

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - micro_network
    restart: always

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - micro_network
    restart: always
    depends_on:
      - prometheus