# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-api'
    static_configs:
      - targets: ['user-api:5001']
    metrics_path: '/metrics'
  - job_name: 'product-api'
    static_configs:
      - targets: ['product-api:5002']
  
  - job_name: 'order-api'
    static_configs:
      - targets: ['order-api:5003']
  
  - job_name: 'frontend-app'
    static_configs:
      - targets: ['frontend-app:5000']
