apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - name: order-db
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pfm_dc_2020
        - name: MYSQL_DATABASE
          value: order
        - name: MYSQL_USER
          value: cloudacademy
        - name: MYSQL_PASSWORD
          value: pfm_2020
        volumeMounts:
        - name: orderdb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: orderdb-storage
        persistentVolumeClaim:
          claimName: orderdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
spec:
  ports:
    - port: 3306
  selector:
    app: order-db
  type: LoadBalancer
