name: Deploy to AWS EKS with SonarQube and Trivy Scanning

on:
  push:
    branches:
      - main  # Trigger when there is a commit to the main branch

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env: 
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
  trivyScan:
    name: Trivy Scan Docker Image
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Trivy
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.22.0_Linux-64bit.deb

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order:latest ./order-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user:latest ./user-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product:latest ./product-service
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest 
          docker push ${{ secrets.DOCKER_USERNAME }}/order:latest 
          docker push ${{ secrets.DOCKER_USERNAME }}/user:latest 
          docker push ${{ secrets.DOCKER_USERNAME }}/product:latest 
      - name: Run Trivy scan on Docker images
        run: |
          trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/order:latest
          trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/user:latest
          trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/product:latest

  deployToEKS:
    name: Deploy to AWS EKS
    runs-on: ubuntu-latest
    needs: trivyScan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.0'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name my-cluster-name  # Replace with your actual cluster name

      - name: Deploy to EKS using kubectl
        run: |
          kubectl apply -f ./kubernetes2
      
          kubectl set image deployment/frontend-deployment frontend=${{ secrets.DOCKER_USERNAME }}/frontend:latest
          kubectl set image deployment/order-api-deployment order-api=${{ secrets.DOCKER_USERNAME }}/order:latest
          kubectl set image deployment/product-api-deployment product-api=${{ secrets.DOCKER_USERNAME }}/product:latest
          kubectl set image deployment/user-api-deployment user-api=${{ secrets.DOCKER_USERNAME }}/user:latest