name: Deploy to AWS EKS with SonarQube and Trivy Scanning

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set-timestamp.outputs.timestamp }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set timestamp
        id: set-timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

  trivyFileScan:
    name: Trivy Scan Files
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Install Trivy
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.22.0_Linux-64bit.deb
      - name: Run Trivy scan
        run: trivy fs --severity CRITICAL .

  dockerBuildPush:
    name: Build and Push Docker Images
    needs: trivyFileScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker images
        env:
          TAG: ${{ needs.sonarqube.outputs.timestamp }}
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:$TAG ./frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order:$TAG ./order-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user:$TAG ./user-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product:$TAG ./product-service
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Docker images
        env:
          TAG: ${{ needs.sonarqube.outputs.timestamp }}
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:$TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/order:$TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/user:$TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/product:$TAG

  trivyImageScan:
    name: Trivy Scan Docker Images
    needs: [dockerBuildPush, sonarqube]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Trivy
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.22.0_Linux-64bit.deb
      - name: Scan Docker images
        env:
          TAG: ${{ needs.sonarqube.outputs.timestamp }}
        run: |
          trivy image --severity CRITICAL ${{ secrets.DOCKER_USERNAME }}/frontend:$TAG
          trivy image --severity CRITICAL ${{ secrets.DOCKER_USERNAME }}/order:$TAG
          trivy image --severity CRITICAL ${{ secrets.DOCKER_USERNAME }}/user:$TAG
          trivy image --severity CRITICAL ${{ secrets.DOCKER_USERNAME }}/product:$TAG

  deployToEKS:
    name: Deploy to AWS EKS
    needs: [trivyImageScan, sonarqube]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.0'
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name my-cluster-name
      - name: Update Kubernetes manifests with new tag
        env:
          TAG: ${{ needs.sonarqube.outputs.timestamp }}
        run: |
          # Use sed to update image tags in kubernetes manifests
          find ./kubernetes -type f -name "*.yaml" -exec sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/frontend:.*|image: ${{ secrets.DOCKER_USERNAME }}/frontend:$TAG|g" {} +
          find ./kubernetes -type f -name "*.yaml" -exec sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/order:.*|image: ${{ secrets.DOCKER_USERNAME }}/order:$TAG|g" {} +
          find ./kubernetes -type f -name "*.yaml" -exec sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/product:.*|image: ${{ secrets.DOCKER_USERNAME }}/product:$TAG|g" {} +
          find ./kubernetes -type f -name "*.yaml" -exec sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/user:.*|image: ${{ secrets.DOCKER_USERNAME }}/user:$TAG|g" {} +
      - name: Deploy to EKS
        run: |
          kubectl apply -f ./kubernetes